[package]
name = "histogram"
version = "0.1.0"
edition = "2021"
authors = ["MarCarrot"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2"
prettytable-rs = "^0.8"
clap = { version = "3.1.6", features = ["derive"] }
